version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn payfortech.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django



